package org.eclipse.ice.apps.wizard;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class EnvironmentDesign extends VerticalLayout {
	protected CssLayout cssLayoutInstallType;
	protected OptionGroup optionGroupInstallType;
	protected CssLayout cssInstallationOptions;
	protected VerticalLayout envVerticalLayout;
	protected Label dummyLabelUsedForSpacing;
	protected Button btnEnvBack;
	protected Button btnEnvOK;

	public EnvironmentDesign() {
		Design.read(this);
	}
}
